{{- if and .Values.supabase.enabled (not .Values.supabase.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cheese-supabase
  labels:
    {{- include "cheese.componentLabels" (list . "supabase") | nindent 4 }}
stringData:
  postgresPassword: {{ .Values.supabase.secret.postgresPassword | quote }}
  jwtSecret: {{ .Values.supabase.secret.jwtSecret | quote }}
  anonKey: {{ .Values.supabase.secret.anonKey | quote }}
  serviceRoleKey: {{ .Values.supabase.secret.serviceRoleKey | quote }}
{{- end }}
