apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cheese-data-pvc
  namespace: cheese
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Ti
  storageClassName: cheese-local-manual
