{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cheese-database
  labels:
    {{- include "cheese.componentLabels" (list . "database") | nindent 4 }}
stringData:
  production: {{ .Values.database.secret.production | quote }}
  cheeseLicense: {{ .Values.database.secret.cheeseLicense | quote }}
  discordWebhookUrl: {{ .Values.database.secret.discordWebhookUrl | quote }}
{{- end }}