{{- if .Values.ketcher.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: cheese-ketcher
  labels:
    {{- include "cheese.componentLabels" (list . "ketcher") | nindent 4 }}
spec:
  type: {{ .Values.ketcher.service.type }}
  ports:
    - port: {{ .Values.ketcher.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cheese.componentSelectorLabels" (list . "ketcher") | nindent 4 }}
{{- end }}
