{{- if and .Values.searchUi.enabled (not .Values.searchUi.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cheese-search-ui-secret
  labels:
    {{- include "cheese.componentLabels" (list . "search-ui") | nindent 4 }}
stringData:
  CHEESE_UI_USER_SECRET: {{ .Values.searchUi.secret.cheeseUiUserSecret | quote }}
  SUPABASE_ANON_KEY: {{ .Values.searchUi.secret.supabaseAnonKey | quote }}
  SUPABASE_SERVICE_ROLE_KEY: {{ .Values.searchUi.secret.supabaseServiceRoleKey | quote }}
  VITE_SUPABASE_ANON_KEY: {{ .Values.searchUi.secret.viteSupabaseAnonKey | quote }}
  DISCORD_WEBHOOK_URL: {{ .Values.searchUi.secret.discordWebhookUrl | quote }}
{{- end }}
