TRANSFORMERS:
  morgan: "tanimoto"
  espsim_electrostatic: "espsim"
  espsim_shape: "shapesim"
  active_pairs: "active_pairs"

DIM: "256"

OUTPUT_DIRECTORIES: 
  TEST: "/tmp/test_db" 

DELIMITERS:
  TEST: ","

INDEX_TYPES:
  TEST: "in_memory"


