TRANSFORMERS:
  morgan: "tanimoto"
  espsim_electrostatic: "espsim"
  espsim_shape: "shapesim"
  active_pairs: "active_pairs"

DIM: "256"

VISUALISATION_MODELS_PATH: "/data/on-prem/visualisation_models/models"

OUTPUT_DIRECTORIES: 
  CUSTOM: "/tmp/test_db" 

DELIMITERS:
  CUSTOM: ","

INDEX_TYPES:
  CUSTOM: "in_memory"


