#!/bin/bash
set -e

# Function to display usage
show_help() {
  echo "Usage: cheese extract-dbs [options]"
  echo "Options:"
  echo "  --dest     Destination folder where databases are downloaded"
  echo "  --db_name    Database to extract" 
  echo "  -h, --help       Show this help message"
  exit 1
}


# Helpers 
convert_to_absolute_path() {
    local input_path="$1"

    # Check if the path is already absolute
    if [[ "$input_path" == /* ]]; then
        # It's already absolute, just return it
        echo "$input_path"
    else
        # It's a relative path, convert it to absolute
        echo "$(pwd)/$input_path"
    fi
}


# Check if no arguments are passed
if [ $# -eq 0 ]; then
    # Show help if no arguments
    show_help
    exit 0
fi

# Parse command-line arguments manually
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dest)
    if [ -z "$2" ]; then
        echo "No destination folder was specified!! Please specify it using --dest flag" 
        exit 1
    fi
    dest=$(convert_to_absolute_path $2)
    shift 2
    ;;
    --db_name)
    if [ -z "$2" ]; then
        echo "No database name was specified!! Please specify it using --db_name flag" 
        exit 1
    fi
    db_name=$2
    shift 2
    ;;
    -h|--help)
      show_help
      ;;
    *)
      echo "Unknown option: $1"
      show_help
      ;;
  esac
done


extract_data(){
  local source_dir=$1
  local parent=$2
  rm -rf "$source_dir/my_data.tar.gz"
  echo "Extracting data in folder $source_dir"
  for file in $source_dir/*.tar*; do
  echo "Extracting file $file"
  cat $file >> "$source_dir/my_data.tar.gz"
  echo "Removing file $file"
  rm -rf $file
  done

  cd $source_dir

  tar -xzvf my_data.tar.gz
  rm -rf my_data.tar.gz

  cd $parent
}


cd $dest
for folder in *; do
  if [[ "$folder" == *"$db_name"* ]]; then
    echo "Extracting $db_name..."
    if find "$folder" -maxdepth 1 -type f -name "*.tar*" | grep -q .; then
      extract_data $folder $dest
      folder_basename=$(basename $folder)
      mv $dest/$folder_basename/$folder_basename/* $dest/$folder_basename   
      rm -rf $dest/$folder_basename/$folder_basename/
    fi
  fi
done

