#!/bin/bash

# Function to display usage
show_help() {
  echo "Usage: cheese generate-license-key"
  echo "Generating the CHEESE license key for this machine"
  echo "Options:"
  echo "  -h, --help       Show this help message"
  exit 1
}


# Parse command-line arguments manually
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      show_help
      ;;
    *)
      echo "Unknown option: $1"
      show_help
      ;;
  esac
done


FULL_IMAGE_NAME="cheese.azurecr.io/on-prem/cheese-database/$CHEESE_CUSTOMER"

set -e

docker run -it -w /opt/cheese/cheese_database --entrypoint python $FULL_IMAGE_NAME -c "from generate_license_ID import main;print('Your license key is'); main()"