#!/bin/bash

# Function to display usage
show_help() {
  echo "Usage: cheese generate-license-key"
  echo "Generating the CHEESE license key for this machine"
  echo "Options:"
  echo "  -h, --help       Show this help message"
  exit 1
}


# Parse command-line arguments manually
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      show_help
      ;;
    *)
      echo "Unknown option: $1"
      show_help
      ;;
  esac
done


IMAGE_NAME="themamaai.azurecr.io/cheese/cheese-api"
FULL_IMAGE_NAME="${IMAGE_NAME}/${CHEESE_CUSTOMER}"

set -e

docker run --privileged -it -w /opt/cheese/cheese_orchestrator --entrypoint python $FULL_IMAGE_NAME -c "from generate_license_ID import main;print('Your license key is :',main())"