#!/bin/bash
set -e

# Function to display usage
show_help() {
  echo "Usage: cheese explorer remove-database [options]"
  echo "Options:"
  echo "  --db_name        Name of your database [Default : 'MY_DB'] "
  echo "  -h, --help       Show this help message"
  exit 1
}



# Check if no arguments are passed
if [ $# -eq 0 ]; then
    # Show help if no arguments
    show_help
    exit 0
fi


db_name="MY_DB"


# Parse command-line arguments manually
while [[ $# -gt 0 ]]; do
  case "$1" in
    # DB name
    --db_name)
    db_name=$2
    shift 2
    ;;
    -h|--help)
      show_help
      ;;
    *)
      echo "Unknown option: $1"
      show_help
      ;;
  esac
done






IMAGE_NAME="themamaai.azurecr.io/cheese/cheese-explorer"
FULL_IMAGE_NAME="${IMAGE_NAME}/${CHEESE_CUSTOMER}"

CONFIG_FILE="${HOME}/.config/cheese/cheese-env-file.conf"

if [ "$TESTING" = "true" ] ; then
    CONFIG_FILE="${HOME}/.config/cheese/cheese-env-file-test.conf"
fi


docker run --privileged -u $UID -v /:/external -it \
  -w "/opt/cheese/cheese_explorer_app/on_prem" \
  --entrypoint "python" \
  --env EXT="/external" \
  --env EXPLORER_CONFIG_FILE="${HOME}/.config/cheese/cheese-explorer-conf.yaml" \
  --env-file $CONFIG_FILE \
  --env DB_NAME=$db_name \
   $FULL_IMAGE_NAME remove_database.py
