#!/bin/bash
set -e

random_uuid=$(uuidgen)
test_folder_name="${USER}_cheese_test_${random_uuid}"

echo "TESTING [1/8] : Testing CHEESE inference..."
echo Making test directory
mkdir -p /tmp/$test_folder_name

cheese run-inference --input_file "${REPO_FOLDER}/tests/test_inference.csv" --dest "/tmp/$test_folder_name/test_db" --index_type in_memory --chunk_size 100 --batch_size 32 --valid_smiles 'false' --canonicalize_smiles 'false' --skip_file_headers 'false'
echo ""

echo "TESTING [2/8] : Starting CHEESE server"
cheese start-server
sleep 10
echo ""

echo "TESTING [3/8] : Testing CHEESE embeddings..."
cheese embeddings-cpu --input_file "${REPO_FOLDER}/tests/test_mols.csv" --dest_folder /tmp/$test_folder_name/embs --search_type morgan
echo ""

echo "TESTING [4/8] : Testing CHEESE search..."
cheese search --input_file "${REPO_FOLDER}/tests/test_mols.csv" --output_file /tmp/$test_folder_name/search_results.csv --db_names TEST --search_type espsim_electrostatic --search_quality 'fast' --n_neighbors 50

echo ""
echo "TESTING [5/8] : Testing CHEESE visualize..."
cheese visualize --input_file "${REPO_FOLDER}/tests/test_mols.csv" --dest_folder /tmp/$test_folder_name/visualize --search_type morgan --visualisation_method pca
echo ""

# Testing explorer

EXPLORER_IMAGE="themamaai.azurecr.io/cheese/cheese-explorer/${CHEESE_CUSTOMER}"
echo ""
echo "TESTING [6/8] : Testing CHEESE explorer - adding database..."

if docker image inspect "$EXPLORER_IMAGE" > /dev/null 2>&1; then
    cheese explorer add-database --input_file "${REPO_FOLDER}/tests/test_mols.csv" --db_name MY_DB
else
    echo "Image $EXPLORER_IMAGE does not exist for customer '$CHEESE_CUSTOMER'. Skipping test"
fi


echo ""

echo ""
echo "TESTING [7/8] : Testing CHEESE explorer - removing database..."
if docker image inspect "$EXPLORER_IMAGE" > /dev/null 2>&1; then
    cheese explorer remove-database --db_name MY_DB
else
    echo "Image $EXPLORER_IMAGE does not exist for customer '$CHEESE_CUSTOMER'. Skipping test"
fi

echo ""

echo "TESTING [8/8] : Stopping CHEESE servers..."
rm -rf /tmp/$test_folder_name || true
cheese stop-servers



echo Tests performed successfully !!