#!/bin/bash

echo Downloading CHEESE images...
REPO_NAME="themamaai.azurecr.io/cheese"

if [ "$CHEESE_CUSTOMER" = 'test' ] ; then
docker login -u cheese-test -p $CHEESE_PASSWORD $REPO_NAME
else
docker login -u $CHEESE_CUSTOMER -p $CHEESE_PASSWORD $REPO_NAME
fi

# Pull the CHEESE app images
echo "Images included in package :" $CHEESE_PACKAGE
echo "To change the package contents please use cheese update-env"
read -p "Do you want to pull the latest images? (y/n)" answer

case "$answer" in
    [Yy]* )
        echo "Pulling the images according to the above package."
        IFS=',' read -ra strings <<< "$CHEESE_PACKAGE"

        for image_name in "${strings[@]}"; do
            echo "Pulling $image_name"
            docker pull "themamaai.azurecr.io/cheese/$image_name/${CHEESE_CUSTOMER}"

        done
        ;;
    [Nn]* )
        exit 0
        ;;
    * )
        echo "Invalid response. Please enter y or n."
        ;;
esac


# Pull Nginx and Oauth2-proxy images

echo "Pulling nginx image..."
docker pull docker.io/library/nginx:alpine
echo "Pulling oauth2 image..."
docker pull quay.io/oauth2-proxy/oauth2-proxy:latest