#!/bin/bash

echo Downloading CHEESE images...
REPO_NAME="themamaai.azurecr.io/cheese"

if [ "$CHEESE_CUSTOMER" = 'test' ] ; then
docker login -u cheese-test -p $CHEESE_PASSWORD $REPO_NAME
else
docker login -u $CHEESE_CUSTOMER -p $CHEESE_PASSWORD $REPO_NAME
fi

# Pull the CHEESE app images
docker pull "themamaai.azurecr.io/cheese/cheese-ui/${CHEESE_CUSTOMER}"
docker pull "themamaai.azurecr.io/cheese/cheese-database/${CHEESE_CUSTOMER}"
docker pull "themamaai.azurecr.io/cheese/cheese-api/${CHEESE_CUSTOMER}"
docker pull "themamaai.azurecr.io/cheese/cheese_inference/${CHEESE_CUSTOMER}"
docker pull "themamaai.azurecr.io/cheese/cheese-explorer/${CHEESE_CUSTOMER}"
