#!/bin/bash

# Pull from repo only in usage mode
echo "Pulling from repo"
cd $REPO_FOLDER
git pull


set -e
# This script moves all bash scripts to $HOME/.local/bin 
# for the purpose of local & production testing on the CHEESE Dev VM

cd "${REPO_FOLDER}/scripts"
echo Installing CHEESE scripts...

# Check if file exists
if [ ! -e "$file" ]; then
  echo "File $file does not exist !!"
  exit 1
fi

for file in *; do
  # Check if the file ends with .sh
  if [[ "$file" != *.sh ]]; then
    # If the file does not end with .sh, print its name
    echo "Moved $file to $HOME/.local/bin"
    cp $file $HOME/.local/bin/
    echo Setting permissions for $HOME/.local/bin/$file
    chmod +x $HOME/.local/bin/$file

  fi
done

cp "${REPO_FOLDER}/install/cheese-env.sh" ${HOME}/.config/cheese
cp "${REPO_FOLDER}/assets/check_database_server.py" ${HOME}/.config/cheese

chmod -R 777 ${HOME}/.config/cheese